---
- hosts: all
  roles:
    - epel-repo
    - rdo-repo
    - chrony
    - { role: ansible-timezone, timezone: UTC }
- hosts: controller
  roles:
    - openstack-controller
  environment:
    OS_USERNAME: admin
    OS_TOKEN: openstack
    OS_URL: http://controller:35357/v3
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3
- hosts: compute*
  roles:
    - openstack-compute-node
